In [11]:
from scipy.cluster.hierarchy import linkage, dendrogram
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import seaborn as sns
from sklearn.cluster import AgglomerativeClustering, KMeans
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA
import seaborn as sns
from mlxtend.frequent_patterns import apriori, association_rules
import gradio as gd

In [3]:
df = pd.read_csv(r"C:\Users\Administrator.DAI-PC2\Desktop\ML\Day12\CatalogCrossSell.csv")
df.head()

,Clothing Division,Housewares Division,Health Products Division,Automotive Division,Personal Electronics Division,Computers Division,Garden Division,Novelty Gift Division,Jewelry Division
0,0,1,1,1,1,0,0,1,0
1,0,1,1,1,1,0,1,1,1
2,0,1,1,1,1,0,1,1,1
3,0,0,1,1,1,0,1,1,0
4,0,0,1,0,1,0,1,1,0

In [4]:
#create frequent itemsets
df = df.astype(bool)
itemsets = apriori(df, min_support=0.2, use_colnames=True)

In [6]:
#and convert into rules
rules = association_rules(itemsets, metric='confidence', min_threshold=0.6)
rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]

,antecedents,consequents,support,confidence,lift
0,(Housewares Division),(Health Products Division),0.393557,1.0,1.0
1,(Personal Electronics Division),(Health Products Division),0.467387,1.0,1.0
2,(Garden Division),(Health Products Division),0.272109,1.0,1.0
3,(Novelty Gift Division),(Health Products Division),0.227491,1.0,1.0
4,(Jewelry Division),(Health Products Division),0.356943,1.0,1.0
5,"(Housewares Division, Personal Electronics Div...",(Health Products Division),0.235494,1.0,1.0

In [7]:
rules.sort_values(by=['lift'], ascending=False).head(6)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(Housewares Division),(Health Products Division),0.393557,1.0,0.393557,1.0,1.0,0.0,inf,0.0
1,(Personal Electronics Division),(Health Products Division),0.467387,1.0,0.467387,1.0,1.0,0.0,inf,0.0
2,(Garden Division),(Health Products Division),0.272109,1.0,0.272109,1.0,1.0,0.0,inf,0.0
3,(Novelty Gift Division),(Health Products Division),0.227491,1.0,0.227491,1.0,1.0,0.0,inf,0.0
4,(Jewelry Division),(Health Products Division),0.356943,1.0,0.356943,1.0,1.0,0.0,inf,0.0
5,"(Housewares Division, Personal Electronics Div...",(Health Products Division),0.235494,1.0,0.235494,1.0,1.0,0.0,inf,0.0

In [8]:
rule_df = rules.sort_values(by=['lift', 'confidence'], ascending=False)
rule_df[['antecedents', 'consequents', 'support', 'confidence', 'lift']]

,antecedents,consequents,support,confidence,lift
0,(Housewares Division),(Health Products Division),0.393557,1.0,1.0
1,(Personal Electronics Division),(Health Products Division),0.467387,1.0,1.0
2,(Garden Division),(Health Products Division),0.272109,1.0,1.0
3,(Novelty Gift Division),(Health Products Division),0.227491,1.0,1.0
4,(Jewelry Division),(Health Products Division),0.356943,1.0,1.0
5,"(Housewares Division, Personal Electronics Div...",(Health Products Division),0.235494,1.0,1.0

In [10]:
relv_rules = rule_df[rule_df['lift']>1]
relv_rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]

Empty DataFrame
Columns: [antecedents, consequents, support, confidence, lift]
Index: []